title: Uhhhhhhh
author: bob
email: s@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Learning Github


# social links
twitter_username: NoTwitter
github_username:  sk

show_excerpts: true # set to false to remove excerpts on the homepage
